Replace deprecated command with environment file
Qiskit/gh-actions pull request #43
Opened 2023-04-03 00:20 UTC by jongwooo

## Description

Resolve  #42 

Update `.github/workflows/code-engine-preview.yml` to use environment file instead of deprecated `set-output` command. 
For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

I found the workflow files that use `set-output` command through the following command:

```bash
$ find . -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```

**AS-IS**

```yml
if ibmcloud ce app list -q | grep "${{ env.APP_NAME }}" ; then
  echo "::set-output name=command::update"
else
  echo "::set-output name=command::create"
fi
```

**TO-BE**

```yml
if ibmcloud ce app list -q | grep "${{ env.APP_NAME }}" ; then
  echo "command=update" >> $GITHUB_OUTPUT
else
  echo "command=create" >> $GITHUB_OUTPUT
fi
```

2023-04-03 00:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Qiskit/gh-actions?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Qiskit/gh-actions?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Qiskit/gh-actions?pullRequest=43) it.</sub>

2023-04-05 02:54 UTC, vabarbosa requested changes
@jongwooo thank you very much for this. i believe line # 166 shouls also be updated:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/13156555/229969174-9e2c4dfd-4b35-4641-adf5-b1dce3715c85.png">

2023-04-05 05:14 UTC, jongwooo commented on .github/workflows/code-engine-preview.yml
> +          )" >> $GITHUB_OUTPUT
@vabarbosa Thank you for your review. I just pushed a commit!

2023-06-01 03:28 UTC, vabarbosa approved these changes
thank you @jongwooo 
my apologies for the late response

2023-06-01 03:28 UTC, merged